title: Jade Gosar # your name (or website title) here
logo: "/images/Profile_picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Jade Gosar and I am a data analyst that has a passion for analytics and its intersection with sport and business. My portfolio contains projects completed through my my 3+ years of experience working as a data analyst in
  non-profit and sports environments as well as my graduate and undergraduate studies.
  <br><br>
  <p><a href="https://www.linkedin.com/in/jade-gosar">View My LinkedIn Profile</a></p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
